Repository 0xProject/OpenZKP, pull requests merged in 2019-10, with the labels that each got.

#370 Remco/optim/lde
  algebra/primefield/src/fft.rs
  crypto/openstark/src/polynomial.rs
  crypto/openstark/src/prover.rs
  utils/mmap-vec/src/mmap_vec.rs
Labels: wip

#384 Set correct outcome value
  crypto/stark/examples/large_fib.rs
Labels: bug

#376 Mason/feature/quickcheck
  .circleci/config.yml
  crypto/stark/src/constraints.rs
  crypto/stark/src/prover.rs
  crypto/stark/src/traits.rs
  crypto/stark/src/verifier.rs
Labels: enhancement

#395 Add long range trace constraints
  crypto/stark/src/constraints.rs
  crypto/stark/src/prover.rs
  crypto/stark/src/rational_expression.rs
  crypto/stark/src/traits.rs
  crypto/stark/src/verifier.rs
Labels: enhancement, wip

#404 Mason/test/starkdex
  crypto/stark/examples/starkdex/constraints.rs
  crypto/stark/examples/starkdex/main.rs
  notebook/starkdex/constraints.rs
  notebook/starkdex/generate_constraints.py
Labels: enhancement, hack, wip

#405 Mason/test/periodic
  crypto/stark/examples/starkdex/constraints.rs
  crypto/stark/examples/starkdex/main.rs
  crypto/stark/examples/starkdex/periodic_columns.rs
  notebook/starkdex/coefficients.rs
  notebook/starkdex/get_coefficients.py
Labels: enhancement
