Repository 0xProject/OpenZKP, pull requests merged in 2019-09, with the labels that each got.

#46 Add MerkleTree
  stark/benches/benchmark.rs
  stark/src/channel.rs
  stark/src/hash.rs
  stark/src/hashable.rs
  stark/src/lib.rs
  stark/src/merkle.rs
  stark/src/merkle_tree/commitment.rs
  stark/src/merkle_tree/index.rs
  stark/src/merkle_tree/mod.rs
  stark/src/merkle_tree/node.rs
  stark/src/merkle_tree/proof.rs
  stark/src/merkle_tree/result.rs
  stark/src/merkle_tree/tree.rs
  stark/src/merkle_tree/vector_commitment.rs
  stark/src/mmap_vec.rs
  stark/src/proofs.rs
  stark/src/utils.rs
  stark/src/verifier.rs
Labels: refactor, wip

#95 Refactor proof of work into own module
  stark/src/channel.rs
  stark/src/lib.rs
  stark/src/proof_of_work.rs
  stark/src/proof_params.rs
  stark/src/proofs.rs
  stark/src/verifier.rs
Labels: refactor

#41 Add RationalExpression
  stark/src/constraint_system.rs
  stark/src/constraints.rs
  stark/src/fibonacci2.rs
  stark/src/rational_expression.rs
Labels: enhancement, wip

#113 Optimize merkle tree
  stark/src/merkle_tree/commitment.rs
  stark/src/merkle_tree/index.rs
  stark/src/merkle_tree/mod.rs
  stark/src/merkle_tree/tree.rs
  stark/src/merkle_tree/vector_commitment.rs
  stark/src/mmap_vec.rs
  stark/src/proofs.rs
Labels: enhancement

#117 Minor fixes in Stark
  stark/Cargo.toml
  stark/examples/large_fib.rs
  stark/examples/small_fib.rs
  stark/src/fibonacci.rs
  stark/src/pedersen_merkle/constraints.rs
  stark/src/pedersen_merkle/inputs.rs
  stark/src/proof_of_work.rs
  stark/src/proofs.rs
  stark/src/verifier.rs
  substrate-runtime/src/block_proof.rs
Labels: enhancement

#141 MiMC example constraint systems
  crypto/openstark/src/algebraic_dag.rs
  crypto/openstark/src/lib.rs
  crypto/openstark/src/mimc/mimc_table_degree.rs
  crypto/openstark/src/mimc/mimc_table_memory.rs
  crypto/openstark/src/mimc/mod.rs
  crypto/openstark/src/proofs.rs
Labels: wip

#331 Cleanup AlgebraicDag
  algebra/primefield/src/field.rs
  crypto/openstark/src/algebraic_dag.rs
  crypto/openstark/src/channel.rs
  crypto/openstark/src/proofs.rs
  crypto/openstark/src/rational_expression.rs
Labels: refactor

#143 Track more stats in allocator
  utils/logging-allocator/src/lib.rs
  utils/logging-allocator/src/logging_allocator.rs
  utils/logging-allocator/src/size_bytes.rs
Labels: enhancement, wip

#346 Document proof and verify
  crypto/openstark/Cargo.toml
  crypto/openstark/Readme.md
  crypto/openstark/src/proofs.rs
  crypto/openstark/src/verifier.rs
Labels: enhancement, wip

#364 Remco/refactor/openstark
  .cargo/config
  .circleci/config.yml
  crypto/openstark/benches/benchmark.rs
  crypto/openstark/examples/large_fib.rs
  crypto/openstark/examples/mimc_cubic.rs
  crypto/openstark/examples/mimc_quadratic.rs
  crypto/openstark/examples/pedersen_merkle/constraints.rs
  crypto/openstark/examples/pedersen_merkle/inputs.rs
  crypto/openstark/examples/pedersen_merkle/main.rs
  crypto/openstark/examples/pedersen_merkle/pedersen_points.rs
  crypto/openstark/examples/pedersen_merkle/periodic_columns.rs
  crypto/openstark/examples/pedersen_merkle/trace_table.rs
  crypto/openstark/examples/small_fib.rs
  crypto/openstark/examples/vdf.rs
  crypto/openstark/src/constraints.rs
  crypto/openstark/src/fibonacci.rs
  crypto/openstark/src/lib.rs
  crypto/openstark/src/mimc/mod.rs
  crypto/openstark/src/pedersen_merkle/mod.rs
  crypto/openstark/src/polynomial.rs
  crypto/openstark/src/prover.rs
  crypto/openstark/src/traits.rs
  crypto/openstark/src/verifier.rs
Labels: wip
