Repository 0xProject/OpenZKP, pull requests merged in 2019-11, with the labels that each got.

#407 Mason/test/trace
  crypto/stark/examples/starkdex/constraints.rs
  crypto/stark/examples/starkdex/inputs.rs
  crypto/stark/examples/starkdex/main.rs
  crypto/stark/examples/starkdex/pedersen.rs
  crypto/stark/examples/starkdex/pedersen_points.rs
  crypto/stark/examples/starkdex/trace_table.rs
  crypto/stark/src/pedersen.rs
Labels: enhancement

#409 Mason/fix/starkdex constraints
  crypto/stark/examples/starkdex/constraints.rs
  crypto/stark/examples/starkdex/inputs.rs
  notebook/starkdex/constraints.rs
  notebook/starkdex/generate_constraints.py
Labels: bug

#410 Mason/test/trace
  crypto/stark/examples/starkdex/constraints.rs
  crypto/stark/examples/starkdex/inputs.rs
Labels: bug

#411 Add ClaimPolynomial
  crypto/stark/examples/starkdex/constraints.rs
  crypto/stark/examples/starkdex/inputs.rs
Labels: enhancement

#412 Degrees for RationalExpression's with denominators
  crypto/stark/src/rational_expression.rs
Labels: enhancement

#415 Remco/feature/composing
  crypto/stark/Cargo.toml
  crypto/stark/src/component.rs
  crypto/stark/src/lib.rs
  crypto/stark/src/rational_expression.rs
  crypto/stark/src/trace_table.rs
  notebook/Composing.md
  notebook/Workshop.md
  utils/mmap-vec/src/mmap_vec.rs
Labels: wip

#431 Componentize pedersen_merkle
  algebra/elliptic-curve/src/lib.rs
  algebra/primefield/Cargo.toml
  algebra/primefield/benchmarks/matter/src/lib.rs
  algebra/primefield/benchmarks/src/main.rs
  algebra/primefield/src/lib.rs
  algebra/primefield/src/rand.rs
  algebra/u256/Cargo.toml
  algebra/u256/src/lib.rs
  algebra/u256/src/rand.rs
  crypto/elliptic-curve-crypto/src/lib.rs
  crypto/hash/src/lib.rs
  crypto/merkle-tree/src/lib.rs
  crypto/stark/Cargo.toml
  crypto/stark/examples/pedersen_merkle/component.rs
  crypto/stark/examples/pedersen_merkle/inputs.rs
  crypto/stark/examples/pedersen_merkle/main.rs
  crypto/stark/examples/pedersen_merkle/pedersen_points.rs
  crypto/stark/examples/pedersen_merkle/starkware_example.rs
  crypto/stark/src/component.rs
  crypto/stark/src/lib.rs
  lints.rs
  utils/criterion-utils/src/lib.rs
  utils/error-utils/src/lib.rs
  utils/logging-allocator/src/lib.rs
  utils/macros-decl/src/lib.rs
  utils/macros-impl/src/lib.rs
  utils/macros-lib/src/lib.rs
  utils/mmap-vec/src/lib.rs
Labels: refactor, wip

#435 Export check_constraints
  crypto/stark/Cargo.toml
  crypto/stark/src/constraint_check.rs
  crypto/stark/src/lib.rs
Labels: enhancement
