Repository 0xProject/OpenZKP, pull requests merged in 2020-03, with the labels that each got.

#571 Add x coordinate method
  algebra/elliptic-curve/src/curve.rs
Labels: enhancement

#107 Implement Radix-√ fft
  .cargo/config
  algebra/primefield/Benchmark.ipynb
  algebra/primefield/Cargo.toml
  algebra/primefield/Readme.md
  algebra/primefield/bench.sh
  algebra/primefield/benches/benchmark.rs
  algebra/primefield/benches/fft.rs
  algebra/primefield/benches/field.rs
  algebra/primefield/benches/permute.rs
  algebra/primefield/benches/transpose.rs
  algebra/primefield/examples/fft.rs
  algebra/primefield/fft.sh
  algebra/primefield/proptest-regressions/fft/depth_first.txt
  algebra/primefield/proptest-regressions/fft/mod.txt
  algebra/primefield/proptest-regressions/fft/radix_sqrt.txt
  algebra/primefield/proptest-regressions/fft/small.txt
  algebra/primefield/proptest-regressions/fft/transpose.txt
  algebra/primefield/src/fft/bit_reverse.rs
  algebra/primefield/src/fft/depth_first.rs
  algebra/primefield/src/fft/iterative.rs
  algebra/primefield/src/fft/mod.rs
  algebra/primefield/src/fft/radix_sqrt.rs
  algebra/primefield/src/fft/small.rs
  algebra/primefield/src/fft/transpose.rs
  algebra/primefield/src/prime_field.rs
  algebra/primefield/src/traits.rs
  utils/logging-allocator/src/logging_allocator.rs
  utils/mmap-vec/Cargo.toml
  utils/mmap-vec/src/mmap_vec.rs
Labels: on hold, performance, wip

#607 New solidity verifier
  .gitignore
  crypto/stark-verifier-ethereum/.gitattributes
  crypto/stark-verifier-ethereum/.gitignore
  crypto/stark-verifier-ethereum/Readme.md
  crypto/stark-verifier-ethereum/buidler.config.ts
  crypto/stark-verifier-ethereum/contracts/hashing.sol
  crypto/stark-verifier-ethereum/contracts/public_coin.sol
  crypto/stark-verifier-ethereum/contracts/testing_contracts/public_coin_tester.sol
  crypto/stark-verifier-ethereum/package-lock.json
  crypto/stark-verifier-ethereum/package.json
  crypto/stark-verifier-ethereum/scripts/sample-script.js
  crypto/stark-verifier-ethereum/test/public_coin_test.ts
  crypto/stark-verifier-ethereum/test/test_utils.ts
  crypto/stark-verifier-ethereum/tsconfig.json
Labels: enhancement, refactor, wip

#503 Assembly routines using ADX extensions (>= Broadwell / Ryzen)
  .cargo/config
  algebra/primefield/Cargo.toml
  algebra/u256/Cargo.toml
  algebra/u256/benches/benchmark.rs
  algebra/u256/src/algorithms/assembly.rs
  algebra/u256/src/algorithms/limb_operations.rs
  algebra/u256/src/algorithms/mod.rs
  algebra/u256/src/algorithms/montgomery/mod.rs
  algebra/u256/src/algorithms/montgomery/proth.rs
  algebra/u256/src/lib.rs
Labels: on hold, performance

#613 Add ecc ScalarFieldElement and Signature types
  algebra/elliptic-curve/benches/benchmark.rs
  algebra/elliptic-curve/src/curve.rs
  algebra/elliptic-curve/src/jacobian.rs
  algebra/elliptic-curve/src/lib.rs
  algebra/elliptic-curve/src/scalar_field.rs
  algebra/elliptic-curve/src/wnaf.rs
  algebra/u256/src/algorithms/mod.rs
  crypto/elliptic-curve-crypto/benches/benchmark.rs
  crypto/elliptic-curve-crypto/src/lib.rs
Labels: refactor
